### ISSUE TITLE
czesc filmow nie zapisuje

### ISSUE THREAD

**Issue by bartekdcm** [JSerwatka/Filmweb2Letterboxd#1]
siemka. z gory zaznacze ze nie jestem programista :)
filmy z data obejrzenia wczesniejsza niz data zalozenia konta nie sa umieszczane w liscie
pozdro

**Comment by JSerwatka** [comment]
@bartekdcm Hej, dzięki za zgłoszenie, postaram się to jak najszybciej sprawdzić 😉
