### ISSUE TITLE
Co jeśli po skrócie klawiszowym ctrl + shift + j nie wyskakuje okno z konsolą tylko takie coś. co robić dalej w takim przypadku?

### ISSUE THREAD

**Issue by RizzerDiamond** [JSerwatka/Filmweb2Letterboxd#15]
![12](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/168966963/629dab4b-3dfc-4a14-ab00-652f81203ab5)

**Comment by JSerwatka** [comment]
Hej, otworzyłeś dobre okno. 
![IMG_20240507_000402](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/33938646/cf8105f3-d176-46d1-84b2-476f18a50751)

Ten chaos który widzisz to tylko wiadomości. Możesz je zignorować. Kliknij tam, gdzie wskazuje strzałka (niebieski znak większości >). Powinna zacząć migać ta kreska, która informuje że możesz coś wpisać . Wklej odpowiedni kod i naciśnij enter. Po jakimś czasie powinno zacząć się ściągać. 
Okno u Ciebie wygląda inaczej, bo ja mam pozmieniane kilka ustawień. 

@RizzerDiamond daj znać czy Ci się udało ogarnąć

**Comment by JSerwatka** [comment]
@RizzerDiamond zamykam
