### ISSUE TITLE
Eksport "Chcę obejrzeć" razem z "Nie interesuje mnie" 

### ISSUE THREAD

**Issue by grbrr** [JSerwatka/Filmweb2Letterboxd#16]
Eksport filmów "Chcę obejrzeć" powoduje również eksport filmów z zaznaczoną opcją "Nie interesuje mnie".

**Comment by JSerwatka** [comment]
@grbrr Dzięki za zgłoszenie! Postaram się spojrzeć na to w tym tygodniu

**Comment by JSerwatka** [comment]
@grbrr nowa wersja dostępna tutaj:
filmy: https://github.com/JSerwatka/Filmweb2Letterboxd/blob/fix/not-interested-movies-donwload-in-watchlist/watchlist_film.js
seriale: https://github.com/JSerwatka/Filmweb2Letterboxd/blob/master/watchlist_serial.js
Sprawdź proszę, czy działa jak należy
