### ISSUE TITLE
Problem z wczytaniem filmów do Letterboxd

### ISSUE THREAD

**Issue by chmuraasia** [JSerwatka/Filmweb2Letterboxd#18]
hej, zrobiłam wszystko zgodnie z instrukcją, kod działa, plik się pobiera ale przy próbie wczytania ich na stronie letterboxda wyskakuje błąd :( 

![lboxd](https://github.com/user-attachments/assets/8719f1d1-16b6-420f-a7b7-3581c3a1d1f7)
![lboxd2](https://github.com/user-attachments/assets/437e3abb-e3b7-43aa-aef8-b8add7f4f8c2)

**Comment by JSerwatka** [comment]
Hej @chmuraasia 👋
Możliwe, że przez jakiś czas występował problem po stronie Letterboxd. Sprawdziłem przed chwilą na swoim komputerze i wszystko działa poprawnie. Jeśli ponownie próbujesz i nadal otrzymujesz błąd, spróbujmy następujących kroków:

1. Jeśli korzystasz z importera filmów obejrzanych (https://letterboxd.com/import), upewnij się, że wczytujesz plik wygenerowany przez ten skrypt: [watched](https://github.com/JSerwatka/Filmweb2Letterboxd/blob/master/watched_film.js). Plik powinien mieć w nazwie słowo "watched", np. "Filmweb2Letterboxd_watched_film_0".
2. Jeśli korzystasz z importera listy filmów "do obejrzenia" https://letterboxd.com/<twój_username>/watchlist/, upewnij się, że wczytujesz plik wygenerowany przez ten skrypt: [watchlist](https://github.com/JSerwatka/Filmweb2Letterboxd/blob/master/watchlist_film.js). Plik powinien zawierać słowo "watchlist", np. "Filmweb2Letterboxd_watchlist_film_0".
3. Jeśli próbujesz wczytać seriale, mogą wystąpić problemy, ponieważ Letterboxd ma ograniczoną bazę danych seriali (platforma skupia się głównie na filmach), więc niektórych tytułów może brakować.

Jeśli problem nadal występuje, możemy podjąć kilka działań:
1. Możesz wysłać plik wyeksportowany przez skrypt (_Filmweb2Letterboxd_watched_film_0_), a ja spróbuję użyć go na swoim komputerze, aby sprawdzić, czy problem leży po stronie pliku. Plik możesz przesłać na adres jserwatka.dev@gmail.com lub dodać go do tej dyskusji.
2. Możemy spróbować zidentyfikować błąd na stronie Letterboxd — w tym celu wyślesz mi kilka zrzutów ekranu. To jednak ostateczność, ponieważ jest bardziej skomplikowane, więc na razie skupmy się na wcześniejszych krokach.

**Comment by JSerwatka** [comment]
@chmuraasia proszę bardzo i miłego korzystania z Letterboxd  😉
