### ISSUE TITLE
wyskakuje błąd i nie wiem o co chodzi :(

### ISSUE THREAD

**Issue by danya288** [JSerwatka/Filmweb2Letterboxd#19]
Robię coś źle? Czy to nie moja wina?
![Screenshot (260)](https://github.com/user-attachments/assets/1b99f38b-fc98-4368-9fad-6f7f83f78919)

**Comment by JSerwatka** [comment]
Hej @danya288 
Postaram się w tym tygodniu spojrzeć

**Comment by JSerwatka** [comment]
Wygląda na to, że z jakimś jednym filmem jest problem. 
Spróbuj proszę tę wersję:
[watched_test.txt](https://github.com/user-attachments/files/17291511/watched_test.txt)

**Comment by JSerwatka** [comment]
Zgaduję, że to jest błąd po stronie Filmwebu. Film został usunięty albo zmieniono mu id

**Comment by danya288** [comment]
Znów takie coś, myślę że spróbuję po prostu usunąć ten film znajdując go po dacie i może się uda.
![image](https://github.com/user-attachments/assets/2d661e26-9dc3-4fda-af0e-41376b489eec)

**Comment by JSerwatka** [comment]
wiem właśnie, na szybko robiłem i błąd popełniłem, sprawdź teraz:

[watched_test.txt](https://github.com/user-attachments/files/17291637/watched_test.txt)

**Comment by danya288** [comment]
udało się! jak wrócę z pracy to spróbuję do letterboxd zimportować

**Comment by JSerwatka** [comment]
oki, jakby coś poszło nie tak przy imporcie to daj znać 😉
