### ISSUE TITLE
Nie działający skrypt albo ja idiota xD

### ISSUE THREAD

**Issue by Setiye** [JSerwatka/Filmweb2Letterboxd#8]
Cześć mam problem wyskakuje mi błąd dokładnie ten: a jaki i ż jestem w tym zielony nie mam pojęcia o co chodzi. Z góry dzięki za odpowiedź.
![obraz_2024-01-11_154657058](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/156334914/44e572d3-58b0-4a43-9d38-7452caf9b211)
![obraz_2024-01-11_154710649](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/156334914/75ab44d4-efd6-4f1b-b3be-178c349ab3e8)
![obraz_2024-01-11_154727743](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/156334914/a4b8a13b-670b-4cef-8e58-53d123c66a70)

**Comment by JSerwatka** [comment]
Hej @Setiye, nie każdy zna się na programowaniu, a skrypt jest dla wszystkich, więc nie ma głupich pytań tutaj 😉
Widzę, że wkleiłeś ten kod do konsoli windowsa. Kod ten działa jednak tylko w przeglądarce, przejdziemy przez to krok po kroku.
1. Otwórz przeglądarkę, najlepiej Chrome.
2. Przejdź na stronę filmweb, zaloguj się i dalej do swojego konta
![image](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/33938646/ae24bc59-c8a0-451c-b5f6-5be9be84a233)
3. Następnie, kliknij na oceny
![image](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/33938646/5752b737-87db-4fb3-9514-53fd318ef67d)
4. Naciśnij `Ctrl +Shift +J` (windows) lub `Cmd + Option + J` (Mac) - w Twoim przypadku będzie to ten pierwszy skrót
5. Powinno pojawić się takie okno (na dole lub po prawej)
![image](https://github.com/JSerwatka/Filmweb2Letterboxd/assets/33938646/694d884c-908d-4c8b-b6fd-42aba0716c0f)
6. Jeśli chcesz ściągnąć obejrzane filmy, to skopiuj zawartość tego pliku https://github.com/JSerwatka/Filmweb2Letterboxd/blob/master/watched.js i wklej do tego okna, co się otworzyło punkt 5)
7. Pliki, które zostaną ściągnięte, wrzuć po zalogowaniu się tutaj: https://letterboxd.com/import/

Uwaga!
Jeśli pojawia Ci się podczas ściągania taki komunikat:
```
VM1671:160 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'href')
at getAllRates (:160:62)
at async main (:215:18)
```
Przejdź do tego problemu: #7 (jesteśmy w trakcie rozwiązywania tego problemu, ale kod, który jest na samym dole tej dyskusji powinien działać)

**Comment by Setiye** [comment]
Dziękuje bardzo, nie miałem z niczym problemu, wszystko ładnie się pobrało. Dzięki za poświęcony czas i chęci, wszystkiego dobrego :D

**Comment by JSerwatka** [comment]
a proszę bardzo, również życzę wszystkiego dobrego i polecam się na przyszłość 😄
